
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 883458
	#The name of the modpack
	modpackName = "NST Trails & Tales"
	#The version of the modpack
	modpackVersion = "1.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

