
["ChocoboKnights of the Crafting Table Config: Config Gear Weapon: Stats involving weapon/shaffron/wingblades"]
	armorAluminum = 0.0
	armorBone = 0.0
	armorBronze = 0.0
	armorChain = 0.0
	armorConstantan = 0.0
	armorCopper = 0.0
	armorDesh = 0.0
	armorDiamond = 0.0
	armorElectrum = 0.0
	armorElementium = 0.0
	armorEmerald = 0.0
	armorFerrous = 0.0
	armorGold = 0.0
	armorHeavyDuty = 0.0
	armorInvar = 0.0
	armorIron = 0.0
	armorLead = 0.0
	armorLeather = 0.0
	armorManasteel = 0.0
	armorMithril = 0.0
	armorNetherite = 0.0
	armorNickel = 0.0
	armorObsidian = 0.0
	armorPlatinum = 0.0
	armorScale = 0.0
	armorSilver = 0.0
	armorSteel = 0.0
	armorStudded = 0.0
	armorTerrasteel = 0.0
	armorTin = 0.0
	armorTitanium = 0.0
	armorToughnessAluminum = 0.0
	armorToughnessBone = 0.0
	armorToughnessBronze = 0.0
	armorToughnessChain = 0.0
	armorToughnessConstantan = 0.0
	armorToughnessCopper = 0.0
	armorToughnessDesh = 0.0
	armorToughnessDiamond = 0.0
	armorToughnessElectrum = 0.0
	armorToughnessElementium = 0.0
	armorToughnessEmerald = 0.0
	armorToughnessFerrous = 0.0
	armorToughnessGold = 0.0
	armorToughnessHeavyDuty = 0.0
	armorToughnessInvar = 0.0
	armorToughnessIron = 0.0
	armorToughnessLead = 0.0
	armorToughnessLeather = 0.0
	armorToughnessManasteel = 0.0
	armorToughnessMithril = 0.0
	armorToughnessNetherite = 0.0
	armorToughnessNickel = 0.0
	armorToughnessObsidian = 0.0
	armorToughnessPlatinum = 0.0
	armorToughnessScale = 0.0
	armorToughnessSilver = 0.0
	armorToughnessSteel = 0.0
	armorToughnessStudded = 0.0
	armorToughnessTerrasteel = 0.0
	armorToughnessTin = 0.0
	armorToughnessTitanium = 0.0
	attackAluminum = 5.0
	attackBone = 4.5
	attackBronze = 6.0
	attackChain = 2.0
	attackConstantan = 5.5
	attackCopper = 5.0
	attackDesh = 6.5
	attackDiamond = 7.0
	attackElectrum = 4.5
	attackElementium = 6.0
	attackEmerald = 9.0
	attackFerrous = 6.5
	attackGold = 4.0
	attackHeavyDuty = 6.0
	attackInvar = 6.5
	attackIron = 6.0
	attackLead = 5.0
	attackLeather = 1.0
	attackManasteel = 6.0
	attackMithril = 8.0
	attackNetherite = 7.0
	attackNickel = 6.5
	attackObsidian = 6.17
	attackPlatinum = 7.5
	attackScale = 4.3
	attackSilver = 4.5
	attackSteel = 6.5
	attackStudded = 2.0
	attackTerrasteel = 7.0
	attackTin = 5.0
	attackTitanium = 8.0
	followRangeAluminum = 0.0
	followRangeBone = 0.0
	followRangeBronze = 0.0
	followRangeChain = 0.0
	followRangeConstantan = 0.0
	followRangeCopper = 0.0
	followRangeDesh = 0.0
	followRangeDiamond = 0.0
	followRangeElectrum = 0.0
	followRangeElementium = 0.0
	followRangeEmerald = 0.0
	followRangeFerrous = 0.0
	followRangeGold = 0.0
	followRangeHeavyDuty = 0.0
	followRangeInvar = 0.0
	followRangeIron = 0.0
	followRangeLead = 0.0
	followRangeLeather = 0.0
	followRangeManasteel = 0.0
	followRangeMithril = 0.0
	followRangeNetherite = 0.0
	followRangeNickel = 0.0
	followRangeObsidian = 0.0
	followRangePlatinum = 0.0
	followRangeScale = 0.0
	followRangeSilver = 0.0
	followRangeSteel = 0.0
	followRangeStudded = 0.0
	followRangeTerrasteel = 0.0
	followRangeTin = 0.0
	followRangeTitanium = 0.0
	knockbackResistanceAluminum = 0.0
	knockbackResistanceBone = 0.0
	knockbackResistanceBronze = 0.0
	knockbackResistanceChain = 0.0
	knockbackResistanceConstantan = 0.0
	knockbackResistanceCopper = 0.0
	knockbackResistanceDesh = 0.0
	knockbackResistanceDiamond = 0.0
	knockbackResistanceElectrum = 0.0
	knockbackResistanceElementium = 0.0
	knockbackResistanceEmerald = 0.0
	knockbackResistanceFerrous = 0.0
	knockbackResistanceGold = 0.0
	knockbackResistanceHeavyDuty = 0.0
	knockbackResistanceInvar = 0.0
	knockbackResistanceIron = 0.0
	knockbackResistanceLead = 0.0
	knockbackResistanceLeather = 0.0
	knockbackResistanceManasteel = 0.0
	knockbackResistanceMithril = 0.0
	knockbackResistanceNetherite = 0.0
	knockbackResistanceNickel = 0.0
	knockbackResistanceObsidian = 0.0
	knockbackResistancePlatinum = 0.0
	knockbackResistanceScale = 0.0
	knockbackResistanceSilver = 0.0
	knockbackResistanceSteel = 0.0
	knockbackResistanceStudded = 0.0
	knockbackResistanceTerrasteel = 0.0
	knockbackResistanceTin = 0.0
	knockbackResistanceTitanium = 0.0
	maxHealthAluminum = 0.0
	maxHealthBone = 0.0
	maxHealthBronze = 0.0
	maxHealthChain = 0.0
	maxHealthConstantan = 0.0
	maxHealthCopper = 0.0
	maxHealthDesh = 0.0
	maxHealthDiamond = 0.0
	maxHealthElectrum = 0.0
	maxHealthElementium = 0.0
	maxHealthEmerald = 0.0
	maxHealthFerrous = 0.0
	maxHealthGold = 0.0
	maxHealthHeavyDuty = 0.0
	maxHealthInvar = 0.0
	maxHealthIron = 0.0
	maxHealthLead = 0.0
	maxHealthLeather = 0.0
	maxHealthManasteel = 0.0
	maxHealthMithril = 0.0
	maxHealthNetherite = 0.0
	maxHealthNickel = 0.0
	maxHealthObsidian = 0.0
	maxHealthPlatinum = 0.0
	maxHealthScale = 0.0
	maxHealthSilver = 0.0
	maxHealthSteel = 0.0
	maxHealthStudded = 0.0
	maxHealthTerrasteel = 0.0
	maxHealthTin = 0.0
	maxHealthTitanium = 0.0
	movementSpeedAluminum = 0.0
	movementSpeedBone = 0.0
	movementSpeedBronze = 0.0
	movementSpeedChain = 0.0
	movementSpeedConstantan = 0.0
	movementSpeedCopper = 0.0
	movementSpeedDesh = 0.0
	movementSpeedDiamond = 0.0
	movementSpeedElectrum = 0.0
	movementSpeedElementium = 0.0
	movementSpeedEmerald = 0.0
	movementSpeedFerrous = 0.0
	movementSpeedGold = 0.0
	movementSpeedHeavyDuty = 0.0
	movementSpeedInvar = 0.0
	movementSpeedIron = 0.0
	movementSpeedLead = 0.0
	movementSpeedLeather = 0.0
	movementSpeedManasteel = 0.0
	movementSpeedMithril = 0.0
	movementSpeedNetherite = 0.0
	movementSpeedNickel = 0.0
	movementSpeedObsidian = 0.0
	movementSpeedPlatinum = 0.0
	movementSpeedScale = 0.0
	movementSpeedSilver = 0.0
	movementSpeedSteel = 0.0
	movementSpeedStudded = 0.0
	movementSpeedTerrasteel = 0.0
	movementSpeedTin = 0.0
	movementSpeedTitanium = 0.0

