
["ChocoboKnights of the Crafting Table Config: Config Gear: Settings involving all gear Currently only enchantability"]
	enchantabilityAluminum = 14
	enchantabilityBone = 7
	enchantabilityBronze = 15
	enchantabilityChain = 12
	enchantabilityConstantan = 12
	enchantabilityCopper = 8
	enchantabilityDesh = 7
	enchantabilityDiamond = 10
	enchantabilityElectrum = 30
	enchantabilityElementium = 7
	enchantabilityEmerald = 14
	enchantabilityFerrous = 18
	enchantabilityGold = 25
	enchantabilityHeavyDuty = 7
	enchantabilityInvar = 16
	enchantabilityIron = 14
	enchantabilityLead = 9
	enchantabilityLeather = 15
	enchantabilityManasteel = 7
	enchantabilityMithril = 12
	enchantabilityNetherite = 10
	enchantabilityNickel = 18
	enchantabilityObsidian = 7
	enchantabilityPlatinum = 16
	enchantabilityScale = 7
	enchantabilitySilver = 25
	enchantabilitySteel = 10
	enchantabilityStudded = 7
	enchantabilityTerrasteel = 7
	enchantabilityTin = 9
	enchantabilityTitanium = 7

