attackKnockbackAluminum = 0.0
attackKnockbackBone = 0.0
attackKnockbackBronze = 0.0
attackKnockbackChain = 0.0
attackKnockbackConstantan = 0.0
attackKnockbackCopper = 0.0
attackKnockbackDesh = 0.0
attackKnockbackDiamond = 0.0
attackKnockbackElectrum = 0.0
attackKnockbackElementium = 0.0
attackKnockbackEmerald = 0.0
attackKnockbackFerrous = 0.0
attackKnockbackGold = 0.0
attackKnockbackHeavyDuty = 0.0
attackKnockbackInvar = 0.0
attackKnockbackIron = 0.0
attackKnockbackLead = 0.0
attackKnockbackLeather = 0.0
attackKnockbackManasteel = 0.0
attackKnockbackMithril = 0.0
attackKnockbackNetherite = 0.0
attackKnockbackNickel = 0.0
attackKnockbackObsidian = 0.0
attackKnockbackPlatinum = 0.0
attackKnockbackScale = 0.0
attackKnockbackSilver = 0.0
attackKnockbackSteel = 0.0
attackKnockbackStudded = 0.0
attackKnockbackTerrasteel = 0.0
attackKnockbackTin = 0.0
attackKnockbackTitanium = 0.0

["ChocoboKnights of the Crafting Table Config: Config Gear Boots: Stats involving boots/talonguards"]
	armorAluminum = 1.0
	armorBone = 2.0
	armorBronze = 3.0
	armorChain = 1.0
	armorConstantan = 2.0
	armorCopper = 1.0
	armorDesh = 4.0
	armorDiamond = 3.0
	armorElectrum = 2.0
	armorElementium = 2.0
	armorEmerald = 5.0
	armorFerrous = 2.0
	armorGold = 1.0
	armorHeavyDuty = 3.0
	armorInvar = 2.0
	armorIron = 2.0
	armorLead = 2.0
	armorLeather = 1.0
	armorManasteel = 2.0
	armorMithril = 4.0
	armorNickel = 2.0
	armorNetherite = 3.0
	armorObsidian = 1.0
	armorPlatinum = 3.0
	armorScale = 3.0
	armorSilver = 2.0
	armorSteel = 3.0
	armorStudded = 1.0
	armorTerrasteel = 3.0
	armorTin = 1.0
	armorTitanium = 5.0
	armorToughnessAluminum = 0.0
	armorToughnessBone = 0.0
	armorToughnessBronze = 1.0
	armorToughnessChain = 0.0
	armorToughnessConstantan = 0.0
	armorToughnessCopper = 0.0
	armorToughnessDesh = 3.0
	armorToughnessDiamond = 2.0
	armorToughnessElectrum = 0.0
	armorToughnessElementium = 0.0
	armorToughnessEmerald = 0.0
	armorToughnessFerrous = 0.0
	armorToughnessGold = 0.0
	armorToughnessHeavyDuty = 1.0
	armorToughnessInvar = 1.0
	armorToughnessIron = 0.0
	armorToughnessLead = 0.0
	armorToughnessLeather = 0.0
	armorToughnessManasteel = 0.0
	armorToughnessMithril = 2.0
	armorToughnessNetherite = 3.0
	armorToughnessNickel = 0.0
	armorToughnessObsidian = 0.0
	armorToughnessPlatinum = 2.0
	armorToughnessScale = 2.0
	armorToughnessSilver = 0.0
	armorToughnessSteel = 2.0
	armorToughnessStudded = 1.0
	armorToughnessTerrasteel = 3.0
	armorToughnessTin = 0.0
	armorToughnessTitanium = 1.0
	attackAluminum = 0.0
	attackBone = 0.0
	attackBronze = 0.0
	attackChain = 0.0
	attackConstantan = 0.0
	attackCopper = 0.0
	attackDesh = 0.0
	attackDiamond = 0.0
	attackElectrum = 0.0
	attackElementium = 0.0
	attackEmerald = 0.0
	attackFerrous = 0.0
	attackGold = 0.0
	attackHeavyDuty = 0.0
	attackInvar = 0.0
	attackIron = 0.0
	attackLead = 0.0
	attackLeather = 0.0
	attackManasteel = 0.0
	attackMithril = 0.0
	attackNetherite = 0.0
	attackNickel = 0.0
	attackObsidian = 0.0
	attackPlatinum = 0.0
	attackScale = 0.0
	attackSilver = 0.0
	attackSteel = 0.0
	attackStudded = 0.0
	attackTerrasteel = 0.0
	attackTin = 0.0
	attackTitanium = 0.0
	attackKnockbackAluminum = 0.0
	attackKnockbackBone = 0.0
	attackKnockbackBronze = 0.0
	attackKnockbackChain = 0.0
	attackKnockbackConstantan = 0.0
	attackKnockbackCopper = 0.0
	attackKnockbackDesh = 0.0
	attackKnockbackDiamond = 0.0
	attackKnockbackElectrum = 0.0
	attackKnockbackElementium = 0.0
	attackKnockbackEmerald = 0.0
	attackKnockbackFerrous = 0.0
	attackKnockbackGold = 0.0
	attackKnockbackHeavyDuty = 0.0
	attackKnockbackInvar = 0.0
	attackKnockbackIron = 0.0
	attackKnockbackLead = 0.0
	attackKnockbackLeather = 0.0
	attackKnockbackManasteel = 0.0
	attackKnockbackMithril = 0.0
	attackKnockbackNetherite = 0.0
	attackKnockbackNickel = 0.0
	attackKnockbackObsidian = 0.0
	attackKnockbackPlatinum = 0.0
	attackKnockbackScale = 0.0
	attackKnockbackSilver = 0.0
	attackKnockbackSteel = 0.0
	attackKnockbackStudded = 0.0
	attackKnockbackTerrasteel = 0.0
	attackKnockbackTin = 0.0
	attackKnockbackTitanium = 0.0
	followRangeAluminum = 0.0
	followRangeBone = 0.0
	followRangeBronze = 0.0
	followRangeChain = 0.0
	followRangeConstantan = 0.0
	followRangeCopper = 0.0
	followRangeDesh = 0.0
	followRangeDiamond = 0.0
	followRangeElectrum = 0.0
	followRangeElementium = 0.0
	followRangeEmerald = 0.0
	followRangeFerrous = 0.0
	followRangeGold = 0.0
	followRangeHeavyDuty = 0.0
	followRangeInvar = 0.0
	followRangeIron = 0.0
	followRangeLead = 0.0
	followRangeLeather = 0.0
	followRangeManasteel = 0.0
	followRangeMithril = 0.0
	followRangeNetherite = 0.0
	followRangeNickel = 0.0
	followRangeObsidian = 0.0
	followRangePlatinum = 0.0
	followRangeScale = 0.0
	followRangeSilver = 0.0
	followRangeSteel = 0.0
	followRangeStudded = 0.0
	followRangeTerrasteel = 0.0
	followRangeTin = 0.0
	followRangeTitanium = 0.0
	knockbackResistanceAluminum = 0.0
	knockbackResistanceBone = 0.0
	knockbackResistanceBronze = 0.0
	knockbackResistanceChain = 0.0
	knockbackResistanceConstantan = 0.0
	knockbackResistanceCopper = 0.0
	knockbackResistanceDesh = 0.0
	knockbackResistanceDiamond = 0.0
	knockbackResistanceElectrum = 0.0
	knockbackResistanceElementium = 0.0
	knockbackResistanceEmerald = 0.0
	knockbackResistanceFerrous = 0.0
	knockbackResistanceGold = 0.0
	knockbackResistanceHeavyDuty = 0.0
	knockbackResistanceInvar = 0.0
	knockbackResistanceIron = 0.0
	knockbackResistanceLead = 0.0
	knockbackResistanceLeather = 0.0
	knockbackResistanceManasteel = 0.0
	knockbackResistanceMithril = 0.0
	knockbackResistanceNetherite = 0.0
	knockbackResistanceNickel = 0.0
	knockbackResistanceObsidian = 0.0
	knockbackResistancePlatinum = 0.0
	knockbackResistanceScale = 0.0
	knockbackResistanceSilver = 0.0
	knockbackResistanceSteel = 0.0
	knockbackResistanceStudded = 0.0
	knockbackResistanceTerrasteel = 0.15
	knockbackResistanceTin = 0.0
	knockbackResistanceTitanium = 0.0
	maxHealthAluminum = 0.0
	maxHealthBone = 0.0
	maxHealthBronze = 0.0
	maxHealthChain = 0.0
	maxHealthConstantan = 0.0
	maxHealthCopper = 0.0
	maxHealthDesh = 0.0
	maxHealthDiamond = 0.0
	maxHealthElectrum = 0.0
	maxHealthElementium = 0.0
	maxHealthEmerald = 0.0
	maxHealthFerrous = 0.0
	maxHealthGold = 0.0
	maxHealthHeavyDuty = 0.0
	maxHealthInvar = 0.0
	maxHealthIron = 0.0
	maxHealthLead = 0.0
	maxHealthLeather = 0.0
	maxHealthManasteel = 0.0
	maxHealthMithril = 0.0
	maxHealthNetherite = 0.0
	maxHealthNickel = 0.0
	maxHealthObsidian = 0.0
	maxHealthPlatinum = 0.0
	maxHealthScale = 0.0
	maxHealthSilver = 0.0
	maxHealthSteel = 0.0
	maxHealthStudded = 0.0
	maxHealthTerrasteel = 0.0
	maxHealthTin = 0.0
	maxHealthTitanium = 0.0
	movementSpeedAluminum = 0.0
	movementSpeedBone = 0.0
	movementSpeedBronze = 0.0
	movementSpeedChain = 0.0
	movementSpeedConstantan = 0.0
	movementSpeedCopper = 0.0
	movementSpeedDesh = 0.0
	movementSpeedDiamond = 0.0
	movementSpeedElectrum = 0.0
	movementSpeedElementium = 0.0
	movementSpeedEmerald = 0.0
	movementSpeedFerrous = 0.0
	movementSpeedGold = 0.0
	movementSpeedHeavyDuty = 0.0
	movementSpeedInvar = 0.0
	movementSpeedIron = 0.0
	movementSpeedLead = 0.0
	movementSpeedLeather = 0.0
	movementSpeedManasteel = 0.0
	movementSpeedMithril = 0.0
	movementSpeedNetherite = 0.0
	movementSpeedNickel = 0.0
	movementSpeedObsidian = 0.0
	movementSpeedPlatinum = 0.0
	movementSpeedScale = 0.0
	movementSpeedSilver = 0.0
	movementSpeedSteel = 0.0
	movementSpeedStudded = 0.0
	movementSpeedTerrasteel = 0.0
	movementSpeedTin = 0.0
	movementSpeedTitanium = 0.0

