
["ChocoboKnights of the Crafting Table Config: ConfigServer"]
	#Enable chocobo auras
	chocoboAuraAllowed = true
	#Chocobo aura duration in seconds, this is also how often the aura is triggered. The aura is only triggered whent he duration ends.
	#Range: 10 ~ 600
	chocoboAuraDurationInSeconds = 30
	#Chocobo aura radius in blocks. If this gets to big it could cause massive lag.
	#Range: 0 ~ 100
	chocoboAuraRadius = 16
	#Enable chocobo custom name abilities
	chocoboCustomNameAbilitiesAllowed = true
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceBlack = 45
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceBlue = 45
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceBrown = 75
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceCyan = 75
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceGold = 40
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceGreen = 75
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChancePink = 75
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChancePurple = 40
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceRed = 40
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceSilver = 45
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceWhite = 45
	#All Weighted Chances are the chance of one color divided by the sum total of all colors.
	#Range: 0 ~ 1000
	chocoboColorWeightedChanceYellow = 600
	#Seconds until Chocobo Child grows into an Adult (Not yet implmented)
	#Range: 0 ~ 10000000
	chocoboGrowingTime = 10000
	#Seconds until Chocobo Egg Hatches
	#Range: 0 ~ 10000000
	chocoboHatchingTime = 600
	#Light level the materia ore crate provides. only a little
	#Range: 0 ~ 15
	lightLevelMateriaCrate = 5
	#Light level the huge materia provides. only a little
	#Range: 0 ~ 15
	lightLevelMateriaHuge = 7
	#Light level the materia ore provides. only a little
	#Range: 0 ~ 15
	lightLevelMateriaOre = 3
	#Light level the placed tonberry lantern provides. only a little
	#Range: 0 ~ 15
	lightLevelLanternTonberry = 10
	#Range: 0 ~ 1000
	materiaMasteringXpAmount = 10
	#Players Start With Field Guide
	playersStartWithFieldGuide = true
	#Range: 0 ~ 10000
	rainbowChocoboNewColorDelay = 20
	#Range: 0.0 ~ 1.0
	randomCustomNameChance = 0.001
	#Show message for Chocobo Knights Discord Server. (Working on making this client side)
	showMessageForDiscord = false
	#Show message if there is a Chocobo Knights Mod update. (Working on making this client side)
	showMessageForUpdate = false
	#Range: 0.0 ~ 1.0
	tameChanceBomb = 0.15
	#Range: 0.0 ~ 1.0
	tameChanceCactuar = 0.15
	#Range: 0.0 ~ 1.0
	tameChanceCarbuncle = 0.15
	#Range: 0.0 ~ 1.0
	tameChanceChocobo = 0.15
	#Range: 0.0 ~ 1.0
	tameChanceMoogle = 0.15
	#Range: 0.0 ~ 1.0
	tameChanceMoomba = 0.95
	#Range: 0.0 ~ 1.0
	tameChanceRedXIII = 0.95
	#Range: 0.0 ~ 1.0
	tameChanceTonberry = 0.95
	#Materia Capture Crystal can be used on villagers and wandering traders; default true
	materiaCaptureCrystalAllowVillagers = true
	#Materia Capture Crystal can be used on Monsters; default false
	materiaCaptureCrystalAllowMonster = false
	#Materia Capture Crystal can be used on mobs outside of ChocboKnights mod; default true
	materiaCaptureCrystalAllowMobsOtherThanChocoboknightsMob = true
	#Materia Capture Crystal can be used on mobs the player or players team has not tamed if tamable; default true
	materiaCaptureCrystalAllowNonOwnerTeam = true
	#Materia Capture Crystal can be used on tamable mobs that are not tamed.
	materiaCaptureCrystalAllowUntamed = true
	#Materia Capture Crystal can be used when in creative mode even if otherwise not allowed, safety in place to prevent breaking the game; default true
	materiaCaptureCrystalAllowCreativeModeAlwaysWork = true
	#Random chance a materia capture crystal breaks on release.
	#Range: 0.0 ~ 1.0
	materiaCaptureCrystalChanceBreak = 0.05

